repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML>=6.0.12.20240808
          - pydantic>=2.7           # keep mypy happy with pydantic v2
        args: ["--config-file=pyproject.toml"]
