name: CI (conda)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: flowfoundry
          environment-file: environment.yml
          auto-activate-base: false
          use-mamba: true
          python-version: "3.12"

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install -e ".[dev]"

      - name: Lint
        shell: bash -l {0}
        run: ruff check src tests

      - name: Type-check
        shell: bash -l {0}
        run: mypy src

      - name: Test
        shell: bash -l {0}
        run: pytest -q
