name: Release (PyPI via conda)

on:
  push:
    tags:
      - "v*"
      - "*.*.*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: flowfoundry
          environment-file: environment.yml
          auto-activate-base: false
          use-mamba: true
          python-version: "3.12"

      - name: Build artifacts
        shell: bash -l {0}
        run: |
          python -m pip install -U pip build twine
          python -m build
          ls -l dist

      - name: Sanity install wheel
        shell: bash -l {0}
        run: |
          pip install --no-index --find-links dist flowfoundry
          python -c "import flowfoundry as ff; print(ff.__version__, ff.ping())"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
