name: Release (PyPI via conda)

on:
  push:
    tags:
      - "v*"
      - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: flowfoundry
          environment-file: environment.yml
          auto-activate-base: false
          use-mamba: true
          python-version: "3.12"

      - name: Build artifacts
        shell: bash -l {0}
        run: |
          python -m pip install -U pip build twine
          python -m build
          ls -l dist
          python -m twine check dist/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist
      - name: Sanity check dist
        run: |
          ls -R
          test -n "$(ls -A dist)" || { echo "❌ No files in dist/"; exit 1; }
      - name: Publish to PyPI (token or OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
          skip-existing: true
          print-hash: true
          verify-metadata: true
